name: Deploy to inklings.live

on:
  push:
    branches:
      - main  # Trigger deployment on push to the main branch

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftp.inklings.live  # Your FTP server
          username: ${{ secrets.username }}  # Add this in GitHub Secrets
          password: ${{ secrets.password }}  # Add this in GitHub Secrets
          local-dir: ./build/  # Adjust to the directory you want to upload
          server-dir: /public_html/  # Adjust to target directory on server
